version: "3.7"

services:
  backoffice-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 run.py
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ../../app:/home/app
      - ${SERVER_STORAGE_PATH}:/home/app/Resource/Storage