version: "3.7"

services:
  backoffice-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.run:app --host 0.0.0.0 --port ${SERVER_PORT} --reload
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ../../app:/home/app
      - ${SERVER_STORAGE_PATH}:/home/app/Resource/Storage