version: "3.7"

services:
  backoffice-api:
    container_name: aishortsmaker-backoffice-api
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -w 8 -k uvicorn.workers.UvicornWorker run:app -b 0.0.0.0:8081
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ../../app:/home/app
      - ${SERVER_STORAGE_PATH}:/home/app/Resource/Storage