apiVersion: batch/v1
kind: CronJob
metadata:
  name: ai-shorts-maker
spec:
  schedule: "{Scheduler}"
  jobTemplate:
    spec:
      template:
        spec:
          ttlSecondsAfterFinished: 0
          containers:
            - name: core-system
              image: "{dockerFileImage}"
              imagePullPolicy: Always
              volumeMounts:
                - name: shared-data
                  mountPath: /home/app/AI-Shorts-Maker-Service/Resource/{UUID}
                - name: config-dir
                  mountPath: /home/app/AI-Shorts-Maker-Service/Config
              env:
                - name: OPENAI_API_KEY
                  value: "{OPENAI_API_KEY}"
                - name: RESOURCE_PATH
                  value: "{RESOURCE_PATH}"
                - name: UUID
                  value: "{UUID}"
                - name: DB_HOST
                  value: "{DB_HOST}"
                - name: DB_PORT
                  value: "{DB_PORT}"
                - name: DB_USER
                  value: "{DB_USER}"
                - name: DB_PW
                  value: "{DB_PW}"
                - name: DB_NAME
                  value: "{DB_NAME}"
                - name: DB_CHARSET
                  value: "{DB_CHARSET}"
          imagePullSecrets:
            - name: dockerhub-secret
          volumes:
            - name: shared-data
              hostPath:
                path: /home/fileDisk
                type: Directory
            - name: config-dir
              hostPath:
                path: /home/aishortsmaker/Config
                type: Directory
          restartPolicy: OnFailure